# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testRun.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        font = QtGui.QFont()
        font.setFamily("Merriweather")
        self.scrollArea.setFont(font)
        self.scrollArea.setStyleSheet("\n"
"QProgressBar {\n"
"      border: 2px solid grey;\n"
"      border-radius: 5px;\n"
"  }\n"
"\n"
"  QProgressBar::chunk {\n"
"      background-color: rgb(232, 74, 95);\n"
"      width: 20px;\n"
"  }\n"
"QProgressBar {\n"
"      border: 2px solid grey;\n"
"      border-radius: 5px;\n"
"      text-align: center;\n"
"  }\n"
"QPushButton{\n"
"    color: black;\n"
"    background-color: #ccccc;\n"
"     padding: .25em;\n"
"     border: 1px solid black;\n"
"     border-radius: 0.4em;\n"
"}\n"
"\n"
"")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 380, 280))
        self.scrollAreaWidgetContents.setStyleSheet("background-color: rgb(216, 208, 160);")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Merriweather")
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Merriweather")
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton:disabled {\n"
"                        background-color: gray;\n"
"            }\n"
"QPushButton:enabled{\n"
"    background-color: rgb(204, 204, 204);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 4, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Merriweather")
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Merriweather")
        self.progressBar.setFont(font)
        self.progressBar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.progressBar.setMaximum(30)
        self.progressBar.setProperty("value", 25)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 2, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Merriweather")
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1)
        self.calculatedCRLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Merriweather")
        self.calculatedCRLabel.setFont(font)
        self.calculatedCRLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.calculatedCRLabel.setObjectName("calculatedCRLabel")
        self.gridLayout.addWidget(self.calculatedCRLabel, 1, 0, 1, 1)
        self.testCompleteLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.testCompleteLabel.setEnabled(True)
        self.testCompleteLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Merriweather")
        self.testCompleteLabel.setFont(font)
        self.testCompleteLabel.setStyleSheet("")
        self.testCompleteLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.testCompleteLabel.setObjectName("testCompleteLabel")
        self.gridLayout.addWidget(self.testCompleteLabel, 3, 0, 1, 2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_5.setText(_translate("Dialog", "another number"))
        self.pushButton.setText(_translate("Dialog", "Continue"))
        self.label_2.setText(_translate("Dialog", "Calculated CR:"))
        self.label_3.setText(_translate("Dialog", "Simulated CR:"))
        self.calculatedCRLabel.setText(_translate("Dialog", "A  number"))
        self.testCompleteLabel.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#ff0000;\">Test Complete !</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
